language: objective-c
osx_image: xcode8

before_install:
  - pod repo update --silent
  - gem install xcpretty

install:
  - pod install

script:
  - set -o pipefail && xcodebuild -workspace LoginLogoutKata.xcworkspace -scheme 'LoginLogoutKata' -destination 'platform=iOS Simulator,name=iPhone 6s Plus' build test CODE_SIGN_IDENTITY=- | xcpretty -c
